books/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name= 'books'
urlpatterns = [
    path('', views.index, name='index'),
    path('data/<str:txt>', views.data, name='data'),
    path('like/', views.like, name="like"),
    path('unlike/', views.unlike, name="unlike"),
    path('see-like/', views.getLike, name="see-like"),
]

lab_10/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name= 'lab_10'
urlpatterns = [
    path('', views.displayForm, name='displayForm'),
	path('submit/', views.runForm, name='runForm'),
	path('validation/', views.emailValidation, name='emailValidation'),
	path('subscribers/', views.subscribersList, name='subscribers'),
	path('subscribers/data/', views.reqJson, name='data'),
	path('unsubscribe/', views.unsub, name='unsubscribes'),
]

lab_4/urls.py
from django.urls import path
from . import views
app_name = 'lab_4'
urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('biodata/', views.biodata, name='biodata'),
    path('education/', views.education, name='education'),
    path('techskills/', views.techskills, name='techskills'),
    path('whativedone/', views.whativedone, name='whativedone'),
    path('perspective/', views.perspective, name='perspective'),
    path('guestbook/', views.guestbook, name='guestbook'),
]

praktikum/urls.py
from django.conf.urls import include
from django.urls import re_path
from django.contrib import admin
from lab_4.views import home as index
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic.base import RedirectView


urlpatterns = [
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^$', index, name='index'),
    re_path(r'^lab_4/', include('lab_4.urls')),
    re_path(r'^lab_5/', include('lab_5.urls')),
    re_path(r'^lab_6/', include('lab_6.urls')),
    re_path(r'^books/', include('books.urls')),
    re_path(r'^lab_10/', include('lab_10.urls')),
    re_path(r'^final/', include('final.urls')),
]+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

lab_4/models.py
from django.db import models

# Create your models here.

lab_4/views.py
from django.http import HttpResponse
from django.shortcuts import render

def home(request):
    response={}
    return render(request, 'homepix.html', response)

def about(request):
    response={}
    return render(request, 'aboutpix.html', response)

def biodata(request):
    response={}
    return render(request, 'biodatapix.html', response)

def education(request):
    response={}
    return render(request, 'educationpix.html', response)

def techskills(request):
    response={}
    return render(request, 'techskillspix.html', response)

def whativedone(request):
    response={}
    return render(request, 'whativedonepix.html', response)

def perspective(request):
    response={}
    return render(request, 'perspectivepix.html', response)

def guestbook(request):
    response={}
    return render(request, 'guestbookpix.html', response)




    

lab_4/templates/aboutpix.html
{% extends "sidenav.html" %}
{% block content %}
{% load static %}
    <body>
        <div class="container">
                <div class="col-lg-12 col-md-12 col-sm-12 text-center">
                        <img src="{% static "photos/person1.png" %}" class="topleft" alt="Logo Person">
                        <p class="textcenter">ABOUT</p>
                        <p class="textcenter">///</p>
                </div>
        </div>

        <div class="container">
                <div class="col-lg-7 col-md-7 col-sm-7 plain">
                    <img src="{% static "photos/irene1.jpg" %}" class="responsive-abt" alt="Irene Pixelyne"><br>
                    <img src="{% static "photos/orangeredline.png" %}" class="responsive-abt" alt="line"><br>

                        <div class="col-md-4 plain">
                            <a href = "https://www.linkedin.com/in/irene-pixelyne/"><img src="{% static "photos/linkedin.png" %}" class="img-responsive centerpic socmed-logo" alt="Linkedin"><br></a>
                        </div>
                        
                        <div class="col-md-4 plain">
                            <a href = "https://www.instagram.com/irenepixelyne/"><img src="{% static "photos/instagram.png" %}" class="img-responsive centerpic socmed-logo" alt="Instagram"><br></a>
                        </div>
                        
                        <div class="col-md-4 plain">
                            <a href = "https://www.twitter.com/irenepixelyne/"><img src="{% static "photos/twitter.png" %}" class="img-responsive centerpic socmed-logo" alt="Twitter"><br></a>
                        </div>
                </div>
    
                <div class="col-lg-5 col-md-5 col-sm-5 text-center plain">
                    <p class="thick">
                    I’m Irene, an undergraduate studying Information System at Faculty Of Computer Science, University of Indonesia.</p><br>
                    <p class="longtext color">
                    A 19 years old girl currently on her second-year of college. Solid interpersonal skill and willing to help, listen, and learn. 
                        I spend my down time reading or watching movies, but if I’m feeling active i either swim or run. 
                        I enjoy listening to music and discovering different-side of me by listening to various genre. 
                        Also in love with technology, coffee, and dogs.</p>
                        <br><br>
                    <div>
                        <img src="{% static "photos/orangerec.png" %}" alt="Line"><br>
                        <a href="{% url 'biodata' %}" class="longtext">Get more personal</a><br>
                        <img src="{% static "photos/redrec.png" %}" alt="Line"><br>
                    </div>
                </div>
                </div>   

    </body>
{% endblock %}

lab_4/templates/biodatapix.html
{% extends "sidenav.html" %}
{% block content %}
{% load static %}
<body>
        <img src="{% static "photos/3sunflower.png" %}" class="topright" alt="Irene Pixelyne">
        <div class="container">
            <div class="col-lg-12 col-md-12 col-sm-12 text-center">
                <div class="textcenter">
                        <p>ABOUT</p>
                        <p>///</p>
                </div>
                    <img src="{% static "photos/person1.png" %}" class="topleft" alt="Person Logo">
            </div>
        </div>
        <div class="container">
            <div class="col-lg-1 col-md-1 col-sm-1"></div>
                <div class="col-lg-4 col-md-4 col-sm-4 longtext color"><p>
                    Full name: Irene Pixelyne Romauli<br><br>
                    Nick name: Irene<br><br>      
                    Date of birth: 15th June 1999<br><br>  
                    Blood Group: O(+) Positive<br><br>
                    Siblings: 2 sisters<br><br>             
                    City: DKI Jakarta<br><br>             
                    Mobile: (+62)82125949998<br><br>           
                    Line ID: irenepixelyn<br><br>          
                    Email: irene.pixelyne@ui.ac.id<br></p>
                    <img src="{% static "photos/redorangerec.png" %}" class="bioline" alt="Line">
                </div>
                <div class="col-lg-3 col-md-3 col-sm-3"></div>
                <div class="col-lg-4 col-md-4 col-sm-4 plain">
                    <div class="row">
                        <img src="{% static "photos/orangeredrec.png" %}" class="bioline" alt="Line"><br><br>
                    </div>
                    <div class="row">
                        <img src="{% static "photos/irene2.jpg" %}" class="irene2css" alt="My Photo">
                    </div>
                </div>
        </div> 
        
            <div id="imageWrapper2">
                    <img src="{% static "photos/bigsunflower.png" %}" class="bottomImageRightBio" alt="Flower"><br><br>
            </div>
</body>
{% endblock %}

lab_4/templates/educationpix.html
{% extends "sidenav.html" %}
{% block content %}
{% load static %}
<body>
    <img src="{% static "photos/bigsunflower2.png" %}" class="edubigsun" alt="Sunflower">
    <img src="{% static "photos/halfsunflower.png" %}" class="halfsunflower" alt="Sunflower">
 
    <div class="container">
        <div class="col-lg-12 col-md-12 col-sm-12 text-center">
            <p class="textcenter">EDUCATION</p>
            <p class="textcenter">///</p>
            <img src="{% static "photos/school.png" %}" class="topleft" alt="Person Logo">
        </div>
    </div>

    <div class="container">
        <div class="col-lg-5 col-md-5 col-sm-5 text-center color">
            <br><img src="{% static "photos/kuliah.png" %}" class="logo-study" alt="kuliah"><br><br><br>
            <img src="{% static "photos/sma.png" %}" class="logo-study" alt="sma"><br><br><br>
            <img src="{% static "photos/smp.png" %}" class="logo-study" alt="smp"><br><br><br>
            <!--<img src="{% static "photos/sd.jpg" %}" class="logo-study" alt="sd"><br><br><br>-->
        </div>
        <div class="col-lg-7 col-md-7 col-sm-7 plain text-center">
            <br><br><p class="text-education">Faculty of Computer Science, University of Indonesia<br>
                    Major : Information System<br>
                    2017 - now
            </p><br><br><br>
            <p class="text-education">SMAN 81 Jakarta<br>
                    Major : Science<br>
                    2014 - 2017
            </p><br><br><br><br>
            <p class="text-education">SMPK 5 Penabur Jakarta<br>
                    2011 - 2014<br>
            </p><br><br><br><br>
           <!-- <p class="text-education">
                    SD Strada Vanlith II<br>
                    2005 - 2011<br>
            </p><br>-->
        </div>
        <div align="right">
            <img src="{% static "photos/orangerec.png" %}" alt="Line"><br>
            <a href="{% url 'techskills' %}" class="longtext">Click for more!</a><br>
            <img src="{% static "photos/redrecshorter.png" %}" alt="Line"><br>
        </div>
    </div>
</body>
{% endblock %}

lab_4/templates/guestbookpix.html
{% extends "sidenav.html" %}
{% block content %}
{% load static %}
<body>
<!--HEADER-->

<img src="{% static "photos/bigsunflower2.png" %}" class="edubigsun" alt="Sunflower">
<img src="{% static "photos/halfsunflower.png" %}" class="halfsunflower" alt="Sunflower">

<div class="container">
        <div class="col-md-12 text-center">
                <img src="{% static "photos/person1.png" %}" class="responsive-top-right" alt="Person Logo">
                <p class="textcenter">GUEST BOOK</p>
                <p class="textcenter">///</p>
        </div>
    </div>
    
    <!--FORM-->
    <div class="container">
        <div class="col-lg-12 col-md-12 col-sm-12 text-center">
            <div class="formposition">
                <form action="/action_page.php"><br><br>
                    <label for="fname">Name</label><br>
                    <input type="text" id="fname" name="firstname" placeholder="Full name.."><br>
                    <label for="fname">Date</label><br>
                    <input type="date" required="required"><br><br>
                    <label for="email">Email</label><br><br>
                    <input type="email" id="email" name="email" placeholder="test@test.com"><br><br>
                    <label for="lname">Subject</label><br>
                    <input type="text" id="subject" name="subject" placeholder="Subject.."><br><br>
                    <label for="subject">Message</label><br>
                    <textarea rows="2" cols="50" id="message" name="message" placeholder="Write something.." style="height:200px"></textarea><br>
                    <br><input type="submit" value="Submit"><br>
                </form>
            </div>
        </div>
    </div>
    
</body>
{% endblock %}

lab_4/templates/homepix.html
{% extends "sidenav.html" %}
{% block content %}
{% load static %}
    <body>
        <div class="container-float text-center">
            <p class="textcenter" style="margin-top:20px">IRENE PIXELYNE</p>
            <div class="col-lg-12 col-md-12 col-sm-12 plain col-centered">
                <div id="button-position">
                        <p id="long-text-home"><strong>Hello!</strong>
                            I study computer science and this website is created for my web design and programming class. 
                                <br>Thankyou for visiting!
                            </p>
                    <button type="submit" id="button-subscribe">
                        <div class="textcenter1">
                                <a class="textcenter1" href="{% url 'lab_10:displayForm' %}">Subscribe</a></button><br><br>
                                <p id="long-text-home">Check out my stories :</p>
                                <div class="inside">
                                        <a href="{% url 'landing' %}"><p class="textcenter1"><strong>Share your status</strong></p></a>
                                        <a href="{% url 'aboutme' %}"><p class="textcenter1"><strong>JQuery Implementation</strong></p></a>
                                        <a href="{% url 'books:index' %}"><p class="textcenter1"><strong>Favorite books</strong></p></a>
                                </div>
                        </div>
                </div>
            </div>
        </div>
        <img src="{% static 'photos/haha.gif' %}" class="responsive-hp" style=" max-width: 250px;" alt="Homepage">
    </body>
{% endblock %}

lab_4/templates/perspectivepix.html
{% extends "sidenav.html" %}
{% block content %}
{% load static %}
<body>
        <div class="container">
                <img src="{% static "photos/doublesunflower.png" %}" class="img-responsive responsive-top-left-pers" alt="Sunflower">
                <div class="col-lg-12 col-md-12 col-sm-12 text-center">
                        <img src="{% static "photos/eye.png" %}" class="topleft" alt="Person Logo">
                        <p class="textcenter">PERSPECTIVE</p>
                        <p class="textcenter">///</p>
                </div>
            </div>
            <div class="container">
                <div class="col-md-4 col-md-offset-4 color text-center long">
                    <p class="long-text-big"><br>How others describe me <br> in 3 words</p>
                    <img src="{% static "photos/orangeredline.png" %}" class="responsive-abt" alt="line"><br>
                </div>
            </div>
            <div class="container">
                <br><br>
                <div class="col-md-4 plain text-center">
                        <img src="{% static "photos/upi.jpg" %}" alt="Luthfi" style="max-width: 250px; min-width: 20px;">
                        <br><br><br><br>
                        <p class="longtext-thick">Luthfi Sulaiman<br></p>
                        <p class="longtext">2015 Fasilkom Student<br>My Mentor<br>Caring<br>Talkative<br>Fun<br></p>
                </div>
                <div class="col-md-4 plain text-center">
                        <img src="{% static "photos/puri.jpg" %}" alt="Puri" style="max-width: 250px; min-width: 20px;">
                        <br><br><br><br>
                        <p class="longtext-thick">Putri Kinanti<br></p>
                        <p class="longtext">2017 Fasilkom Student<br>My close friend<br>Outgoing<br>Talkative<br>Ambitious<br></p>
                </div>
                <div class="col-md-4 plain text-center">
                    <img src="{% static "photos/budi.jpg" %}" alt="Budiono" style="max-width: 250px; min-width: 20px;">
                    <br><br><br><br>
                    <p class="longtext-thick">M. Arif Budiono<br></p>
                    <p class="longtext">2016 Fasilkom Student<br>My PIC in CGT Pubic Relation<br>Clever<br>Dependable<br>Fierce<br></p>
                </div>
                <div class="col-md-4 plain text-center">
                        <br><br><img src="{% static "photos/fara.jpg" %}" alt="Fahira" style="max-width: 250px; min-width: 20px;">
                        <br><br><br><br><br>
                        <p class="longtext-thick">Fahira Develin<br></p>
                        <p class="longtext">2017 Metallurgy Student ITS<br>My Highschool Bestie<br>Up to date<br>Happy<br>Talkaktive<br></p>
                </div>
                <div class="col-md-4 plain text-center">
                        <br><br><img src="{% static "photos/iqbal.jpg" %}" alt="Iqbal" style="max-width: 250px; min-width: 20px;">
                        <br><br><br><br><br>
                    <p class="longtext-thick">M Iqbal Mahendra<br></p>
                    <p class="longtext">2016 Fasilkom Student<br>My Mentor<br>Diligent<br>Perfectionist<br>Open minded<br></p>
                </div>
                <div class="col-md-4 plain text-center">
                        <br><br><img src="{% static "photos/nadya.jpg" %}" alt="Nadya" style="max-width: 250px; min-width: 20px;">
                        <br><br><br><br><br>
                    <p class="longtext-thick">Nadya Nisrina<br></p>
                    <p class="longtext">2017 Farmacy Student UI<br>My Highschool Bestie<br>Mature<br>Smart<br>Kind<br></p>
                </div>
            </div>

            <div id="imageWrapper2">
                    <img src="{% static "photos/large.png" %}" class="bottomImageRightPers">
            </div>    
</body>
{% endblock %}

lab_4/templates/techskillspix.html
{% extends "sidenav.html" %}
{% block content %}
{% load static %}
<body>
        <img src="{% static "photos/3sunflower.png" %}" class="responsive-3sun" alt="Sunflower">
        <div class="container">
            <div class="col-lg-12 col-md-12 col-sm-12 text-center">
                    <img src="{% static "photos/code.png" %}" class="topleft" alt="Code Logo">
                    <p class="textcenter">EDUCATION</p>
                    <p class="textcenter">///</p>
                    <p class="techinalskillstext">Technical Skills</p>
                    <div class="center-block" id="rectangle5"></div><br>
            </div>
        </div>
        <div class="container">
                <div class="col-lg-1 col-md-1 col-sm-1 text-center"></div>
                <div class="col-lg-3 col-md-3 col-sm-3 text-center color">
                    <p class="page-5-caption">Languange</p>
                    <img src="{% static "photos/wave.png" %}" class="center-block-wave" alt="Wave"><br><Br>
                    <div id="wrapper">
                            <img src="{% static "photos/java.png" %}" class="img-responsive center-block-java hover" alt="Java"><br><br>
                            <p class="text">Java</p>
                            <img src="{% static "photos/python.svg" %}" class="center-block-python hover" alt="Pyhthon"><br><br>
                            <p class="text">Python</p><br><br><br><br><br><br><br><br><br><br><br><br>
                    </div>
                </div>
                <div class="col-lg-1 col-md-1 col-sm-1 text-center"></div>
                <div class="col-lg-3 col-md-3 col-sm-3 text-center color">
                    <p class="page-5-caption">Technologies</p>
                    <img src="{% static "photos/wave.png" %}" class="center-block-wave" alt="Wave"><br><br>
                    <div class="center-block" id="wrapper">
                            <img src="{% static "photos/vsc.png" %}" class="center-block-tech hover" alt="Visual Studio Code"><br><br>
                            <p class="text">Visual Studio Code</p>
                            <img src="{% static "photos/sublime.png" %}" class="center-block-tech hover" alt="Sublime"><br><br>
                            <p class="text">Sublime</p>
                            <img src="{% static "photos/intellij.png" %}" class="center-block-tech hover" alt="Intellij"><br><br>
                            <p class="text">Intellij</p><br><br><br><br><br><br>
                    </div>
                </div>
                <div class="col-lg-1 col-md-1 col-sm-1 text-center"></div>
                <div class="col-lg-3 col-md-3 col-sm-3 text-center color">
                    <p class="page-5-caption">Packages</p>
                    <img src="{% static "photos/wave.png" %}" class="center-block-wave" alt="Wave"><br><br>
                    <div id="wrapper">
                            <img src="{% static "photos/msword.png" %}" class="center-block-tech hover" alt="Microsoft Word"><br><br>
                            <p class="text">Microsoft Word</p>
                            <img src="{% static "photos/msexcel.png" %}" class="center-block-tech hover" alt="Microsoft Excel"><br><br>
                            <p class="text">Microsoft Excel</p>
                            <img src="{% static "photos/mspp.png" %}" class="center-block-tech hover" alt="Microsoft Power Point"><br><br>
                            <p class="text">Microsoft Power Point</p>
                            <img src="{% static "photos/outlook.png" %}" class="center-block-tech hover" alt="Outlook"><br><br>
                            <p class="text">Outlook</p>
                    </div>
                </div>
        </div>
        <div id="imageWrapper2">
            <img src="{% static "photos/sunflowerpg5.png" %}" class="img-responsive bottomImageCenterTech" alt="Sunflower">
        </div>
</body>
{% endblock %}

lab_4/templates/whativedonepix.html
{% extends "sidenav.html" %}
{% block content %}
{% load static %}
<body>
        <img src="{% static "photos/sunflowerpg6.png" %}" class="responsive-what" alt="Sunflower">
        <div class="container">
            <div class="col-md-12 text-center">
                    <img src="{% static "photos/work.png" %}" class="topleft" alt="Work Logo">
                    <p class="textcenter">WHAT I'VE DONE SO FAR</p>
                    <p class="textcenter">///</p>
            </div>
        </div>
        
        <div class="container">
                        <div class="col-lg-12 col-md-12 col-sm-12 plain" id="redrectangle"></div><br>
                        <div class="col-lg-12 col-md-12 col-sm-12 plain" id="orangerectangle"></div><br>
                        <div class="col-lg-2 col-md-2 col-sm-2 plain text-center"></div>
                            <div class="col-lg-4 col-md-4 col-sm-4 color text-center">
                                    <br><p class="thick-small">DIGITAL MARKETING INTERNSHIP</p>
                                    <p class="long-text-small">INews</p>
                                    <p class="long-text-small">2018</p>
                                    <p class="thick-small">PIC OF EVENT</p>
                                    <p class="long-text-small">Open House Fasilkom UI</p>
                                    <p class="long-text-small">2018</p>
                                    <p class="thick-small">VICE PIC OF PUBLIC RELATION</p>
                                    <p class="long-text-small">Pemira Fasilkom UI</p>
                                    <p class="long-text-small">2018</p>
                                    <p class="thick-small">MENTOR OF STUDENT ORIENTATION</p>
                                    <p class="long-text-small">PMB Fasilkom UI</p>
                                    <p class="long-text-small">2018</p>
                                    <p class="thick-small">STAFF OF PLAYGROUND</p>
                                    <p class="long-text-small">COMPFEST X</p>
                                    <p class="long-text-small">2018</p>
                                    <p class="thick-small">STAFF OF PUBLIC RELATION</p>
                                    <p class="long-text-small">The 25th CGT</p>
                                    <p class="long-text-small">2017</p>
                                    <p class="thick-small">STAFF OF PUBLIC RELATION</p>
                                    <p class="long-text-small">Open House Fasilkom UI</p>
                                    <p class="long-text-small">2017</p><br>
                            </div>
                            <div class="col-lg-1 col-md-1 col-sm-1 plain text-center"></div>
                <div class="col-lg-5 col-md-5 col-sm-5">
                    <img src="{% static "photos/ireneanit.jpg" %}" class="fotoberdua" alt="OH 2018">
                    <img src="{% static "photos/pemira.jpg" %}" class="fotoberdua" alt="Pemira 2018">
                    <img src="{% static "photos/cgt2017.jpg" %}" class="fotoberdua" alt="CGT 2017">
                    <img src="{% static "photos/mentor2018.jpg" %}" class="fotoberdua" alt="PMB 2018">
                    <img src="{% static "photos/oh2017.jpg" %}" class="fotoberdua" alt="OH 2017">
                    <img src="{% static "photos/pg2018.jpg" %}" class="fotoberdua" alt="PG 2018">
                </div>
            
        </div>
        <div id="imageWrapper2">
            <img src="{% static "photos/bottomsunflower.png" %}" class="bottomwhat" alt="Sunflower">
        </div>
</body>
{% endblock %}