books/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name= 'books'
urlpatterns = [
    path('', views.index, name='index'),
    path('data/<str:txt>', views.data, name='data'),
    path('like/', views.like, name="like"),
    path('unlike/', views.unlike, name="unlike"),
    path('see-like/', views.getLike, name="see-like"),
]

lab_5/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name = 'lab_5'
urlpatterns = [
	path('', views.displayschedule, name='displayschedule'),
	# path('displayschedule/', views.displayschedule, name='displayschedule'),
	path('makeschedule/', views.makeschedule, name='makeschedule'),
	path('delete/', views.delete, name='delete'),
]

praktikum/urls.py
from django.conf.urls import include
from django.urls import re_path
from django.contrib import admin
from lab_4.views import home as index
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic.base import RedirectView


urlpatterns = [
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^$', index, name='index'),
    re_path(r'^lab_4/', include('lab_4.urls')),
    re_path(r'^lab_5/', include('lab_5.urls')),
    re_path(r'^lab_6/', include('lab_6.urls')),
    re_path(r'^books/', include('books.urls')),
    re_path(r'^lab_10/', include('lab_10.urls')),
    re_path(r'^final/', include('final.urls')),
]+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

lab_5/models.py
from django.db import models
from django.utils import timezone
from datetime import datetime, date

# Create your models here.

class Schedule(models.Model):
    day = models.CharField(max_length=20)
    date = models.DateField()
    time = models.TimeField()
    name = models.CharField(max_length=100)
    place = models.CharField(max_length=140)
    category = models.CharField(max_length=100)
    
    


 

lab_5/forms.py
from django import forms
from .models import Schedule

class ScheduleForm(forms.Form):
    OPTION =(
        ('1', 'Education'),
        ('2', 'Entertaiment'),
        ('3', 'Sports'),
        ('4', 'Arts'),
        ('5', 'Socials'),
        ('6', 'Others'),
    )
    day = forms.CharField(label = "Day",  required = True, max_length=100)
    date = forms.DateField(label = "Date", required = True, widget=forms.DateInput(attrs={'type':'date'}))
    time = forms.TimeField(label = "Time", required = True, widget=forms.TimeInput(attrs={'type':'time'}))
    name = forms.CharField(label = "Activity", required = True, max_length=100)
    place = forms.CharField(label = "Place", required = True, max_length=140)
    category = forms.ChoiceField(label = "Category", required = True, widget=forms.Select(), choices=OPTION)

lab_5/views.py
from django.shortcuts import render, redirect
from .forms import ScheduleForm
from .models import Schedule

# Create your views here.

def displayschedule(request):
    response = {}
    schedules = Schedule.objects.all()
    response = {
        "schedules" : schedules
    }
    return render(request, 'displayschedule.html', response)


def makeschedule(request):
    form = ScheduleForm(request.POST or None)
    response = {}
    if(request.method == "POST"):
        if(form.is_valid()):
            day = request.POST.get("day")
            date = request.POST.get("date")
            time = request.POST.get("time")
            name = request.POST.get("name")
            place = request.POST.get("place")
            category = request.POST.get("category")
            Schedule.objects.create(day=day, date=date, time=time, name=name, place=place, category=category)
            return redirect('displayschedule')
        else:
            return render(request, 'makeschedule.html', response)
    else:
        response['form'] = form
        return render(request, 'makeschedule.html', response)


def delete(request):
    response={}
    schedules = Schedule.objects.all().delete()
    response['schedule'] = schedules
    return render(request, 'displayschedule.html', response)

lab_5/templates/displayschedule.html
{% extends "sidenav.html" %}
{% load static %}
{% block content %}
<body>

        <img src="{% static "photos/bigsunflower2.png" %}" class="edubigsun" alt="Sunflower">
        <img src="{% static "photos/halfsunflower.png" %}" class="halfsunflower" alt="Sunflower">

    <div class="container">
        <div class="col-lg-12 col-md-12 col-sm-12 text-center">
                <img src="{% static "photos/schedule.png" %}" class="responsive-top-right" style="max-width: 50px" alt="Schedule Logo">
                <p class="textcenter">SCHEDULE</p>
                <p class="textcenter">///</p>
        </div>
    </div>
    <div class="container">
            <div class="col-lg-12 col-md-12 col-sm-12">
                    <table style="width:100%">
                        {% if schedules %}
                            <tr>
                                <th>Day</th>
                                <th>Date</th>
                                <th>Time</th>
                                <th>Activity</th>
                                <th>Place</th>
                                <th>Category</th>
                            </tr>
                            {% for schedule in schedules %}
                                <tr>
                                    <td><br>{{ schedule.day }}</td>
                                    <td><br>{{ schedule.date }}</td>
                                    <td><br>{{ schedule.time }}</td>
                                    <td><br>{{ schedule.name }}</td>
                                    <td><br>{{ schedule.place }}</td>
                                    <td><br>{{ schedule.category }}<t/d>
                                </tr>
                            {% endfor %}
                        {% else %}
                            <p class="thick text-center">Yay, no schedule!</p> 
                        {% endif %}
                    </table>
                    <br>
                    <form action="{% url 'lab_5:makeschedule' %}">
                        <a href="{% url 'lab_5:makeschedule' %}" class="longtext-thick">
                            <p class="text-center"><br><br>ADD NEW SCHEDULE</p><br><br>
                        </a>
                    </form>
                    <form action= "{% url 'lab_5:delete' %}">
                        <a href="{% url 'lab_5:delete' %}" class="longtext-thick">
                           <p class="text-center">DELETE ALL SCHEDULE</p> 
                        </a>
                    </form>
                </div>
    </div>
    
</body>
{% endblock %}

lab_5/templates/makeschedule.html
{% extends "sidenav.html" %}
{% load static %}
{% block content %}
<body>

        <img src="{% static "photos/3sunflower.png" %}" class="responsive-3sun" alt="Sunflower">
      
<div class="container">
    <div class="col-lg-12 col-md-12 col-sm-12 text-center">
            <img src="{% static "photos/schedule.png" %}" class="responsive-top-right" style="max-width: 50px" alt="Schedule Logo">
            <p class="textcenter">CREATE SCHEDULE</p>
            <p class="textcenter">///</p>
    </div>
</div>

<div class="container">
    <div class="col-lg-12 col-md-12 col-sm-12 text-center">
        <!-- <div class="roundedrec">
            <div class="insiderec"> -->
                <p class="long-text-big">Lets Get Organized</p><br>
                <form action="#" method="POST">
                    {% csrf_token %}
                    {% for field in form %}
                        <p>{{ field.label_tag }} <br> {{ field }}</p>
                    {% endfor %}
                    <input type="submit" value="Submit"><br><br>
                    <a href="{% url 'lab_5:displayschedule' %}">
                        <p class="thick">See Schedules</p>
                    </a>
                </form>
            <!-- </div>
        </div> -->
    </div>
    
    <style type="text/css">
        label {
            margin-right: 0.7em; /* or larger if you need */
            margin-bottom: -1em;
        }
    </style>
    
</div>
<div id="imageWrapper2">
        <img src="{% static "photos/sunflowerpg5.png" %}" class="img-responsive bottomImageCenterTech" alt="Sunflower">
    </div>


</body>
{% endblock %}