books/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name= 'books'
urlpatterns = [
    path('', views.index, name='index'),
    path('data/<str:txt>', views.data, name='data'),
    path('like/', views.like, name="like"),
    path('unlike/', views.unlike, name="unlike"),
    path('see-like/', views.getLike, name="see-like"),
]

lab_4/urls.py
from django.urls import path
from . import views
app_name = 'lab_4'
urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('biodata/', views.biodata, name='biodata'),
    path('education/', views.education, name='education'),
    path('techskills/', views.techskills, name='techskills'),
    path('whativedone/', views.whativedone, name='whativedone'),
    path('perspective/', views.perspective, name='perspective'),
    path('guestbook/', views.guestbook, name='guestbook'),
]

lab_5/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name = 'lab_5'
urlpatterns = [
	path('', views.displayschedule, name='displayschedule'),
	# path('displayschedule/', views.displayschedule, name='displayschedule'),
	path('makeschedule/', views.makeschedule, name='makeschedule'),
	path('delete/', views.delete, name='delete'),
]

praktikum/urls.py
from django.conf.urls import include
from django.urls import re_path
from django.contrib import admin
from lab_4.views import home as index
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic.base import RedirectView


urlpatterns = [
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^$', index, name='index'),
    re_path(r'^lab_4/', include('lab_4.urls')),
    re_path(r'^lab_5/', include('lab_5.urls')),
    re_path(r'^lab_6/', include('lab_6.urls')),
    re_path(r'^books/', include('books.urls')),
    re_path(r'^lab_10/', include('lab_10.urls')),
    re_path(r'^final/', include('final.urls')),
]+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/sidenav.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <meta charset="UTF-8">
        <title>Pixelyne</title>
        <link rel="icon" href="{% static 'photos/icon.png' %}" type="image/gif" sizes="16x16">
        <meta name="viewport" content="width=device-width, initial-scale=1">
	    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'css/csspix.css' %}" type="text/css">
	    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
        <link rel="stylesheet" media="screen" href="https://fontlibrary.org/face/liberation-sans" type="text/css"/>
    </head>
    <body>
        <div id="mySidenav" class="sidenav">
   
            <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
                <a href="{% url 'lab_4:home' %}">
                    <img src="{% static "photos/home.png" %}" class="home" alt="Back to Home">
                </a>
                <a href="{% url 'lab_4:about' %}" class="textcenter">About</a>
                <a href="{% url 'lab_4:education' %}" class="textcenter">Education</a>
                <a href="{% url 'lab_4:whativedone' %}" class="textcenter">What I've done so far</a>
                <a href="{% url 'lab_4:perspective' %}" class="textcenter">Perspective</a>
                <a href="{% url 'lab_4:guestbook' %}" class="textcenter">Guest Book</a>
                <a href="{% url 'lab_5:displayschedule' %}" class="textcenter">Schedule</a>
            </div>
            <div id="tab">
                <span style="font-size:30px;cursor:pointer" onclick="openNav()">&#9776;</span>
            </div>
            <script>
                function openNav() {
                    document.getElementById("mySidenav").style.width = "250px";
                }
                function closeNav() {
                    document.getElementById("mySidenav").style.width = "0";
                }
            </script>       
            {% block content %}
            {% endblock %} 
        </body>
    </html>