books/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name= 'books'
urlpatterns = [
    path('', views.index, name='index'),
    path('data/<str:txt>', views.data, name='data'),
    path('like/', views.like, name="like"),
    path('unlike/', views.unlike, name="unlike"),
    path('see-like/', views.getLike, name="see-like"),
]

lab_10/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name= 'lab_10'
urlpatterns = [
    path('', views.displayForm, name='displayForm'),
	path('submit/', views.runForm, name='runForm'),
	path('validation/', views.emailValidation, name='emailValidation'),
	path('subscribers/', views.subscribersList, name='subscribers'),
	path('subscribers/data/', views.reqJson, name='data'),
	path('unsubscribe/', views.unsub, name='unsubscribes'),
]

lab_4/urls.py
from django.urls import path
from . import views
app_name = 'lab_4'
urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('biodata/', views.biodata, name='biodata'),
    path('education/', views.education, name='education'),
    path('techskills/', views.techskills, name='techskills'),
    path('whativedone/', views.whativedone, name='whativedone'),
    path('perspective/', views.perspective, name='perspective'),
    path('guestbook/', views.guestbook, name='guestbook'),
]

praktikum/urls.py
from django.conf.urls import include
from django.urls import re_path
from django.contrib import admin
from lab_4.views import home as index
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic.base import RedirectView


urlpatterns = [
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^$', index, name='index'),
    re_path(r'^lab_4/', include('lab_4.urls')),
    re_path(r'^lab_5/', include('lab_5.urls')),
    re_path(r'^lab_6/', include('lab_6.urls')),
    re_path(r'^books/', include('books.urls')),
    re_path(r'^lab_10/', include('lab_10.urls')),
    re_path(r'^final/', include('final.urls')),
]+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

lab_10/models.py
from django.db import models

# Create your models here.
class subscribe(models.Model):
    firstName = models.CharField(max_length=30)
    lastName = models.CharField(max_length=30)
    email = models.EmailField(max_length=30, unique=True)
    password = models.CharField(max_length=30)

lab_10/forms.py
from django import forms

class subscribeForm(forms.Form):

    invalid_message={
        'required' : 'Please fill out this field',
        'invalid' : 'Please fill out with valid Input',
    }

    firstname_attrs={
        'type' : 'text',
        'class' : 'todo-form-input',
        'placeholder' : 'Please enter your first name',
    }

    lastname_attrs={
        'type' : 'text',
        'class' : 'todo-form-input',
        'placeholder' : 'Please enter your first name',
    }

    email_attrs={
        'type' : 'text',
        'class' : 'todo-form-input',
        'placeholder' : 'Please enter a valid email address',
    }

    password_attrs={
        'type' : 'password',
        'class' : 'todo-form-input',
        'placeholder' : 'Password should be a combination of Alphabets and Numbers',
    }

    firstName = forms.CharField(label="First Name", required=True, max_length=30, widget=forms.TextInput(attrs = firstname_attrs))
    lastName = forms.CharField(label="Last Name", required=True, max_length=30, widget=forms.TextInput(attrs = lastname_attrs))
    email = forms.EmailField(label="Email", required=True, max_length=30, widget=forms.TextInput(attrs = email_attrs))
    password = forms.CharField(label="Password", required=True, max_length=30, widget=forms.PasswordInput(attrs = password_attrs))

lab_10/views.py
from django.shortcuts import render, redirect
from django.db import IntegrityError
from django.http import HttpResponse
from .models import subscribe
from .forms import subscribeForm
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse
from django.db import IntegrityError
import json

response = {}
def displayForm(request):
    form = subscribeForm(request.POST or None)
    response['form'] = form
    return render(request, 'subscribe.html', response)

def runForm(request):
    try:
        if(request.method == "POST"):
             firstName = request.POST.get('firstName', None)
             lastName = request.POST.get('lastName', None)
             email = request.POST.get('email', None)
             password = request.POST.get('password', None)
             subscribe.objects.create(firstName=firstName, lastName=lastName, email=email, password=password)
             return HttpResponse(json.dumps({'result' : 'Thankyou ' + firstName + ' for subscribing!'}))
        else:
            return HttpResponse(json.dumps({'result' : 'fail'}))

    except IntegrityError as e:
        return HttpResponse(json.dumps({'result' : 'fail'}))

@csrf_exempt
def emailValidation(request):
    theEmail = request.POST.get('email', None)
    validation = {
        'isTaken' : subscribe.objects.filter(email=theEmail).exists()
    }
    return JsonResponse(validation)

def subscribersList(request):
        response['fill'] = subscribe.objects.all()
        return render(request, 'subscriberList.html', response)

def reqJson(request):
        subscribers = subscribe.objects.all()
        listAll = list()
        for i in subscribers:
                user = {'firstName' : i.firstName, 'lastName' : i.lastName, 'email' : i.email}
                listAll.append(user)
        return HttpResponse(json.dumps({'items': listAll}))

def unsub(request):
        email = request.POST.get('email', None)
        subscribe.objects.all().filter(email=email).delete()
        return HttpResponse(json.dumps({'items':email}))
        

lab_10/templates/subscribe.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Subscribe</title>
    <link rel="icon" href="{% static 'photos/thanks.png' %}" type="image/gif" sizes="16x16">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <link rel="stylesheet" href="{% static 'css/csslab_10.css' %}" type="text/css">
    <script type = "text/javascript" src = "{% static 'js/jslab_10.js' %}" ></script>
    <link href="https://fonts.googleapis.com/css?family=Nunito+Sans|Suez+One" rel="stylesheet">
</head>
<body>
    <div id='fill'>
        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-12">
                    <a href="{% url 'lab_4:home' %}">
                    <img src="{% static "photos/home.png" %}" style="max-width: 30px; margin-top: 20px" alt="Back to Home"></a>
                    <center>
                        <div id="outside2">
                            <div id="inside2">
                                <p class="textcenter1">Keep up with me!</p>
                            </div>
                        </div>
                        <div id="outside">
                            <div id="inside">
                                <form method="POST">
                                    {% csrf_token %}
                                    {% for field in form %}
                                    <p class="label_tag">{{ field.label_tag }} <br> {{ field }}</p>
                                    {% endfor %}
                                    <input style="margin-bottom:10px" disabled=true class="btn btn-info btn-lg" id="submit"  type="submit" value="Submit" >
                                </form>
                                <a href = "{% url 'lab_10:subscribers' %}"><button class="btn btn-info">See Subscribers</button></a>
                            </div>
                    </div>
                </div>
            </div>
        </div>
        <div id="dialog" title="Hey!"></div>
        <div id="waitUp" style="margin-bottom:30vh"></div>
    </div>
</center>
</body>
</html>

lab_10/templates/subscriberList.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
            <meta charset="UTF-8">
            <title>Subscribe</title>
            <link rel="icon" href="{% static 'photos/thanks.png' %}" type="image/gif" sizes="16x16">
            <meta name="viewport" content="width=device-width, initial-scale=1">
            <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
            <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
            <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
            <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
            <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
            <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
            <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
            <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
            <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
            <link rel="stylesheet" href="{% static 'css/csslab_10.css' %}" type="text/css">
            <script type = "text/javascript" src = "{% static 'js/jslab_10.js' %}" ></script>
            <link href="https://fonts.googleapis.com/css?family=Nunito+Sans|Suez+One" rel="stylesheet">
    </head>
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                    <a href="{% url 'lab_4:home' %}">
                            <img src="{% static "photos/home.png" %}" style="max-width: 30px; margin-top: 20px" alt="Back to Home"></a>
                            <center>
                    <div id="outside2">
                            <div id="inside2">
                                <p class="textcenter1">Subscribers List</p>
                            </div>
                        </div>
                    <div id="outside">
                            <div id="inside">
                                    <div id='fill'>
                                                <table id ='data' class="table table-responsive container" style="text-align: center;">
                                                    <tr>
                                                        <th id='table' style="text-align:center">First Name</th>
                                                        <th id='table' style="text-align:center">Last Name</th>
                                                        <th id='table' style="text-align:center">Email</th>
                                                        <th id='table' style="text-align:center">Password</th>
                                                    </tr>
                                                </table>
                                            
                                        </div>
                            </div>
                        </div>
            </div>
        </div>
    </div>
</center>
</html>